constellations:
  version: v1
  kind: Configs # May be [Configs | Secrets | Actions]
  metadata:
    namespace: default
    taskName: default
    queue: default
    forceNamespaceQueue: true
  payload: # May contains [file | env | actions]
    files:
      test: test.env
      test_name: test_name.env
    env:
      NESTO: VAL # key is the name of the env and value is env value [Tombstone] remove env
      NESTO2: VAL2
  strategy:
    type: AtOnce # May be AtOnce | RollingUpdate | Canary
    update: all # May be [all | number] | [percentage of clustr nodes]
    interval: 10d # [ (days | d) (hour | h) | default ]
    retry: 
      strategy: Cancel #[Cancel | LinearBackoff | ConstantBackoff | QuadriaticBackoff | ExponentialBackoff | PolynomialBackoff]
      attempts: 2
      constant: 1 # a step for ConstantBackoff
  selector:
    labels:
      l1: v1
      l2: v2
      l3: v3
    compare:
      kind: all # May be [all | any] 
  # region:
  #   region1:
  #     cluster:
  #       cluster1:
  #       cluster2:
  #   region2:
  #     cluster:
  #       cluster1:
  #       cluster3:
  #       cluster4:
