organization: c12s
name: app_config
version: v1.0.0
createdAt: 2024-05-24 18:45:03 +0000 UTC
paramSets:
    - name: db_config
      paramSet:
        - key: port
          value: "4444"
    - name: media_path_config
      paramSet:
        - key: path
          value: /media
