configurations:
    - organization: c12s
      name: ""
      version: ""
      createdAt: 2024-05-25 14:44:03 +0000 UTC
      paramSet: []
    - organization: c12s
      name: db_config
      version: v1.0.0
      createdAt: 2024-05-25 14:13:50 +0000 UTC
      paramSet:
        - key: address
          value: 127.0.0.1
        - key: port
          value: "1234"
